version: "3"
services:
  app:
    extends:
      file: ./local/docker-compose-local.yaml
      service: app
    environment:
      - DJ_PUBLIC_S3_LOCATION=djhub.vathes.datapub.elements:/workflow-calcium-imaging-data-v2
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
